services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: xv4s6.h.filess.io
      - key: DB_PORT
        value: 3307
      - key: DB_DATABASE
        value: DBdonasi_strawsmoke
      - key: DB_USERNAME
        value: DBdonasi_strawsmoke
      - key: DB_PASSWORD
        value: decf84a16e210b53759367b2821e24d336143c79
